FROM rhscl/mysql-57-rhel7

MAINTAINER mosco mascolo99@gmail.com

ADD http://legacy.redhat.com/pub/redhat/linux/9/en/doc/RH-DOCS/pdf-en/rhl-gsg-es.pdf  /opt/app-root/src

COPY ./mysql /opt/app-root/src

EXPOSE 3306


